In [1]:
#import the necessary packages for analysis
import pandas as pd
import numpy as np
import seaborn as sb
import matplotlib as mb

In [2]:
# load the csv file with all geosmin data and find column data types
geosmin_data = pd.read_csv(r'/Users/maanavjhatakia/Documents/Python.nosync/geosmin/geosmin_data_20122022.csv')
geosmin_data.dtypes

SAMPLE_NUMBER                  int64
SAMPLED_DATE                  object
SAMPLE_NAME                   object
SAMPLING_POINT_DESCRIPTION    object
SITE                          object
FACILITY                      object
SAMPLE_TESTING_LOCATION       object
ANALYSIS                      object
ANALYSIS_DESCRIPTION          object
ANALYTE                       object
ANALYTE_REPORTED_NAME         object
FORMATTED_ENTRY               object
UNITS                         object
dtype: object

In [3]:
# attempted to change the datatype for the ANALYTE column to isolate geosmin data
geosmin_data = geosmin_data.astype({"ANALYTE":str})
geosmin_data.dtypes

SAMPLE_NUMBER                  int64
SAMPLED_DATE                  object
SAMPLE_NAME                   object
SAMPLING_POINT_DESCRIPTION    object
SITE                          object
FACILITY                      object
SAMPLE_TESTING_LOCATION       object
ANALYSIS                      object
ANALYSIS_DESCRIPTION          object
ANALYTE                       object
ANALYTE_REPORTED_NAME         object
FORMATTED_ENTRY               object
UNITS                         object
dtype: object

In [4]:
#extract only the geosmin entries - not dealing with MIB right now
values = ['MIB', 'IBMP', 'IPMP']
geosmin_data = geosmin_data[geosmin_data.ANALYTE.isin(values) == False]

In [5]:
#drop the unnecessary columns to simplify
geosmin_data = geosmin_data.drop(columns = ['ANALYSIS','ANALYSIS_DESCRIPTION','SAMPLE_TESTING_LOCATION','ANALYTE_REPORTED_NAME'])

In [6]:
# get only values from Marston for the analysis from the overall dataframe
facility_values = ['Marston', 'Marston WTP', 'Marston Forebay']
geosmin_data = geosmin_data[geosmin_data.FACILITY.isin(facility_values) == True]

In [7]:
#look at top of geosmin_data dataframe
geosmin_data.head()

,SAMPLE_NUMBER,SAMPLED_DATE,SAMPLE_NAME,SAMPLING_POINT_DESCRIPTION,SITE,FACILITY,ANALYTE,FORMATTED_ENTRY,UNITS
0,220554,6/19/2012 12:57,PL-MAR-EFF,NaN,6100 W Quincy Ave,Marston WTP,Geosmin,2.22,ng/L
2,220592,6/26/2012 12:19,PL-MAR-EFF,NaN,6100 W Quincy Ave,Marston WTP,Geosmin,4.99,ng/L
4,221912,7/2/2012 14:40,RS-MR-01-5,NaN,Marston Reservoir Depth Sampling Location at Buoy,Marston,Geosmin,26.69,ng/L
6,222026,7/10/2012 14:00,RS-MR-01-5,NaN,Marston Reservoir Depth Sampling Location at Buoy,Marston,Geosmin,4.64,ng/L
8,222352,7/18/2012 8:40,RS-MR-01-5,NaN,Marston Reservoir Depth Sampling Location at Buoy,Marston,Geosmin,24.63,ng/L

In [8]:
#conduit 20 at marston forebay influent streams
list_conduit20_sites = ['WS-LP-021','WS-LP-021-4','WS-LP-021-A']

#sample sites at marston reservoirs (varying depths)
list_sample_res_sites = ['RS-MR-01-1','RS-MR-01-10','RS-MR-01-11','RS-MR-01-12', 'RS-MR-01-14','RS-MR-01-15','RS-MR-01-16', 'RS-MR-01-17', 'RS-MR-01-18', 'RS-MR-01-3','RS-MR-01-4', 'RS-MR-01-5', 'RS-MR-01-6', 'RS-MR-01-7', 'RS-MR-01-8', 'RS-MR-01-9', 'RS-MR-01-A-1','RS-MR-01-A-10','RS-MR-01-A-12','RS-MR-01-A-14','RS-MR-01-A-4','RS-MR-01-A-6','RS-MR-01-A-7','RS-MR-01-A-8','RS-MR-01-A-9','RS-MR-01-B','RS-MR-01-B-11','RS-MR-01-B-18','RS-MR-01-B-9','RS-MR-01-I','RS-MR-01-I-4','RS-MR-01-I-6','RS-MR-01-I-7','RS-MR-01-I-8','RS-MR-01-I-9','RS-MR-01-T','RS-MR-01-T-1']

#sample sites at marston WTP at prescribed depth
wtp_sample_list = ['PL-MAR-MLOWH-4','PL-MAR-MLOWH-A-3','PL-MAR-MLOWH-A-4','PL-MAR-MLOWL-10','PL-MAR-MLOWL-A-10','PL-MAR-MLOWL-A-11','PL-MAR-MLOWM','PL-MAR-MLOWM-4','PL-MAR-MLOWM-6','PL-MAR-MLOWM-7','PL-MAR-MLOWM-A','PL-MAR-MLOWM-A-4','PL-MAR-MLOWM-A-5','PL-MAR-MLOWM-A-6','PL-MAR-MLOWM-A-7','PL-MAR-MLOWM-A-9']

# marston wtp influent values
wtp_influent_list = ['PL-MAR-INF','PL-MAR-INF-4','PL-MAR-INF-A']

#separate out different entries based on location of sampling/testing
conduit20_df = geosmin_data.loc[geosmin_data['SAMPLE_NAME'].isin(list_conduit20_sites)]
sample_res_df = geosmin_data.loc[geosmin_data['SAMPLE_NAME'].isin(list_sample_res_sites)]
wtp_samples_df = geosmin_data.loc[geosmin_data['SAMPLE_NAME'].isin(wtp_sample_list)]
wtp_influent_df = geosmin_data.loc[geosmin_data['SAMPLE_NAME'].isin(wtp_influent_list)]

In [9]:
# cleaning out the negligible entries that start with ">" or "<"
conduit20_df = conduit20_df[conduit20_df['FORMATTED_ENTRY'].str[0].isin(['>','<']) == False]

In [10]:
# clean out negligible entries that start with ">" or "<" for other dataframes
sample_res_df = sample_res_df[sample_res_df['FORMATTED_ENTRY'].str[0].isin(['>','<']) == False]

wtp_samples_df = wtp_samples_df[wtp_samples_df['FORMATTED_ENTRY'].str[0].isin(['>','<']) == False]

wtp_influent_df = wtp_influent_df[wtp_influent_df['FORMATTED_ENTRY'].str[0].isin(['>','<']) == False]

In [11]:
sample_res_df

,SAMPLE_NUMBER,SAMPLED_DATE,SAMPLE_NAME,SAMPLING_POINT_DESCRIPTION,SITE,FACILITY,ANALYTE,FORMATTED_ENTRY,UNITS
4,221912,7/2/2012 14:40,RS-MR-01-5,NaN,Marston Reservoir Depth Sampling Location at Buoy,Marston,Geosmin,26.69,ng/L
6,222026,7/10/2012 14:00,RS-MR-01-5,NaN,Marston Reservoir Depth Sampling Location at Buoy,Marston,Geosmin,4.64,ng/L
8,222352,7/18/2012 8:40,RS-MR-01-5,NaN,Marston Reservoir Depth Sampling Location at Buoy,Marston,Geosmin,24.63,ng/L
10,222470,7/25/2012 8:45,RS-MR-01-5,NaN,Marston Reservoir Depth Sampling Location at Buoy,Marston,Geosmin,62.66,ng/L
12,222471,7/25/2012 8:50,RS-MR-01-15,NaN,Marston Reservoir Depth Sampling Location at Buoy,Marston,Geosmin,5.07,ng/L
...,...,...,...,...,...,...,...,...,...
3342,668283,4/21/2020 10:00,RS-MR-01-I-4,NaN,Marston Reservoir Depth Sampling Location at Buoy,Marston,Geosmin,2,ng/L
3345,668292,4/21/2020 10:10,RS-MR-01-B-11,NaN,Marston Reservoir Depth Sampling Location at Buoy,Marston,Geosmin,2,ng/L
3680,801385,10/16/2020 8:58,RS-MR-01-I-4,NaN,Marston Reservoir Depth Sampling Location at Buoy,Marston,Geosmin,14,ng/L
3683,801383,10/16/2020 8:58,RS-MR-01-B-9,NaN,Marston Reservoir Depth Sampling Location at Buoy,Marston,Geosmin,14,ng/L
3685,801381,10/16/2020 8:58,RS-MR-01-T-1,NaN,Marston Reservoir Depth Sampling Location at Buoy,Marston,Geosmin,15,ng/L

In [12]:
sample_res_df['DEPTH'] = sample_res_df['SAMPLE_NAME'].str.split('-').str[3]

In [13]:
wtp_samples_df['DEPTH'] = wtp_samples_df['SAMPLE_NAME'].str.split('-').str[2]

In [14]:
conduit20_df.to_csv('conduit20_geosmin.csv', index=False)

In [15]:
sample_res_df.to_csv('sample_res_geosmin.csv',index = False)

In [16]:
wtp_samples_df.to_csv('wtp_samples_geosmin.csv',index= False)

In [17]:
wtp_influent_df.to_csv('wtp_influent_geosmin.csv',index = False)